---

- name: Make sure passenger prerequisites are installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - epel-release
    - pygpgme
  become: yes
  tags:
    - passenger

- name: Import the passenger gpg key
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{passenger_yum_repo_gpg_urls}}"
  register: import_key
  become: yes
  tags:
    - passenger

- name: add passenger repository
  yum_repository:
    name: passenger
    description: Repository with Passenger RPM packages for CentOS 7
    baseurl: https://oss-binaries.phusionpassenger.com/yum/passenger/el/$releasever/$basearch
    gpgkey: "{{ passenger_yum_repo_gpg_urls[1] }}"
    gpgcheck: "{{ passenger_gpg_check }}"
    repo_gpgcheck: "{{ passenger_repo_gpgcheck }}"
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Make cache
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='passenger'"
  when: passenger_make_cache and import_key.changed
  become: yes

- name: Install the passenger repository
  yum:
    name: mod_passenger
    state: installed
    update_cache: yes
  become: yes
  notify: restart apache
  tags:
    - passenger
